### ISSUE TITLE
Seems to require msfrpc which isn't in pypi/pip

### ISSUE THREAD

**Issue by kyhwana** [maxwellkoh/2FAssassin#3]
msfrpc doesn't appear to be in pip/pypi:
Processing dependencies for 2fassassin==2.0
Searching for msfrpc
Reading https://pypi.python.org/simple/msfrpc/
Couldn't find index page for 'msfrpc' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for msfrpc
error: Could not find suitable distribution for Requirement.parse('msfrpc')

python --version
Python 2.7.12

pymetasploit in pip appears to be a different module/package.

**Comment by maxwellkoh** [comment]
https://github.com/SpiderLabs/msfrpc/tree/master/python-msfrpc
