### ISSUE TITLE
import Spider in assassin.py leads to error

### ISSUE THREAD

**Issue by MacBachi** [maxwellkoh/2FAssassin#4]
Following the installation instructions, assassin.py leads to the following error when started:
`# python ./assassin.py -h`
leads to:
```
Traceback (most recent call last):
 [...]
     import Spider
 ImportError: No module named Spider
```

**Comment by sieunhando** [comment]
I got it too

**Comment by maxwellkoh** [comment]
ignore that module (test class) by commenting it.
e.g.,
# import Spider

**Comment by kinggdiamond** [comment]
keep getting import modul 7 msfrp
